/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { Abi } from "viem";
import PaythenaAutomationDeployment from "~~/generated/deployments/bleTestnet/PaythenaAutomation.json";
import PaythenaCoreDeployment from "~~/generated/deployments/bleTestnet/PaythenaCore.json";
import PaythenaLoanDeployment from "~~/generated/deployments/bleTestnet/PaythenaLoan.json";
import PaythenaStakingDeployment from "~~/generated/deployments/bleTestnet/PaythenaStaking.json";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  52085143: {
    // BLE Testnet
    PaythenaCore: {
      address: "0xcC16052C70f7188DC724D420Fc6fb284026877f7",
      abi: PaythenaCoreDeployment.abi as Abi,
    },
    PaythenaLoan: {
      address: PaythenaLoanDeployment.address,
      abi: PaythenaLoanDeployment.abi as Abi,
    },
    PaythenaStaking: {
      address: PaythenaStakingDeployment.address,
      abi: PaythenaStakingDeployment.abi as Abi,
    },
    PaythenaAutomation: {
      address: PaythenaAutomationDeployment.address,
      abi: PaythenaAutomationDeployment.abi as Abi,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
